### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by responderi** [doc97/Gwent#1]
_Projekti ladattu torstaina 10:47_
# Palaute
Tästä palautteesta tulee aika positiivishenkinen, koska omaan silmääni ei hirveästi särähtänyt mikään. Koodissa ja ohjelman toiminnallisuudessa on selkeä rakenne ja hyvin suunniteltu kokonaisuus. Luokat noudattavat single-responsibility periaatetta ja ovat yksikäsitteisiä. Metodit eivät ole ylipitkiä (poislukien tietenkin graaffinen toteutus, mutta siinä ne lieneekin hyväksyttävää) ja niiden toiminnallisuus on helposti ymmärrettävää. Turhaa copy-pastea ei esiinny ja olin positiivisesti yllättynyt kuinka valmiiksi GUI oli saatu. Testit olivat kattavat ja keskittyivät nimenomaan logiikkaan.

**Comment by doc97** [comment]
Hei! Kiitos palautteesta, olet vissiin aika uusi kehittäjä ja ymmärrän jos oli vaikeeta lukea läpi kaikki koodini :). Hyvä asia on että ymmärsit koodin loogista rakennetta, sillä tällöin se on riittävän selkeä. Oletko varma ettet löydä mitään parannettavaa? :)
